import {
  ShipmentItem,
  Order,
  LowStockAlert,
  ConsumptionLog,
  Vendor,
  HeatmapNode,
  UrgentAlert,
  Invoice,
} from './types';

export const initialShipments: ShipmentItem[] = [
  {
    id: '#SHP-8821',
    origin: 'Regional Depot A',
    destination: 'Primary Health Centre, Malda',
    status: 'In Transit',
    date: 'Today, 09:30 AM',
    itemsCount: 450,
    priority: true,
  },
  {
    id: '#SHP-8819',
    origin: 'Central Warehouse',
    destination: 'Primary Health Centre, Malda',
    status: 'Received',
    date: 'Yesterday',
    itemsCount: 1200,
    priority: false,
  },
  {
    id: '#SHP-8815',
    origin: 'Supplier Direct',
    destination: 'Primary Health Centre, Malda',
    status: 'Delayed',
    date: 'Oct 24',
    itemsCount: 300,
    priority: true,
  },
  {
    id: '#SHP-8809',
    origin: 'District Depot B',
    destination: 'City Hospital North Wing',
    status: 'Received',
    date: 'Oct 22',
    itemsCount: 820,
    priority: false,
  },
];

export const initialLowStockAlerts: LowStockAlert[] = [
  {
    id: 'LSA-1',
    drugName: 'Paracetamol 500mg (Tab)',
    batchNo: 'B-7742',
    currentUnits: 15,
    minThreshold: 50,
    unitType: 'Units',
    severity: 'critical',
    location: 'Pharmacy Shelf A-2',
    daysSupplyRemaining: 2,
  },
  {
    id: 'LSA-2',
    drugName: 'Saline IV Fluid (500ml)',
    batchNo: 'IV-091',
    currentUnits: 42,
    minThreshold: 40,
    unitType: 'Units',
    severity: 'warning',
    location: 'Fluids Rack 4',
    daysSupplyRemaining: 4,
  },
  {
    id: 'LSA-3',
    drugName: 'Amoxicillin 250mg (Cap)',
    batchNo: 'AX-112',
    currentUnits: 100,
    minThreshold: 100,
    unitType: 'Units',
    severity: 'warning',
    location: 'Antibiotics Cabinet',
    daysSupplyRemaining: 5,
  },
  {
    id: 'LSA-4',
    drugName: 'Insulin Glargine (100IU/ml)',
    batchNo: 'C-112',
    currentUnits: 8,
    minThreshold: 30,
    unitType: 'Vials',
    severity: 'critical',
    location: 'Cold Storage 1 (4°C)',
    daysSupplyRemaining: 1.5,
  },
];

export const initialConsumptionLogs: ConsumptionLog[] = [
  {
    id: 'LOG-1',
    wardName: 'Maternity Ward',
    icon: 'local_hospital',
    timestamp: '10 mins ago',
    items: [
      { name: 'Oxytocin Injection', quantity: 10, unit: 'Ampoules' },
    ],
    requestedBy: 'Dr. Sharma',
    issuedBy: 'Admin',
  },
  {
    id: 'LOG-2',
    wardName: 'Emergency Dept (ER)',
    icon: 'healing',
    timestamp: '1 hour ago',
    items: [
      { name: 'Gauze Rolls', quantity: 50, unit: 'Rolls' },
      { name: 'Surgical Tape', quantity: 10, unit: 'Packs' },
    ],
    requestedBy: 'ER Nurse Station',
    issuedBy: 'Admin',
  },
  {
    id: 'LOG-3',
    wardName: 'Pediatric ICU',
    icon: 'child_care',
    timestamp: '3 hours ago',
    items: [
      { name: 'Paracetamol Syrup 120mg', quantity: 15, unit: 'Bottles' },
      { name: 'IV Cannula 24G', quantity: 20, unit: 'Units' },
    ],
    requestedBy: 'Dr. Banerjee',
    issuedBy: 'Admin',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ORD-8942',
    orderNumber: 'ORD-2023-8942',
    destination: 'City Hospital North Wing',
    requestedDate: 'Oct 24, 08:30 AM',
    status: 'Ready for Dispatch',
    priority: true,
    clearedForDispatch: true,
    slaLimit: '4 hrs remaining',
    totalValue: '₹18,450',
    transportDocStatus: 'Pending Generation',
    manifest: [
      {
        id: 'M-1',
        drugName: 'Amoxicillin 500mg Caps',
        batchNo: 'B-992-X',
        quantity: 5000,
        unit: 'Caps',
        status: 'Packed',
        location: 'Aisle 2, Shelf A',
      },
      {
        id: 'M-2',
        drugName: 'Ibuprofen 400mg Tabs',
        batchNo: 'B-104-Y',
        quantity: 2500,
        unit: 'Tabs',
        status: 'Packed',
        location: 'Aisle 3, Shelf C',
      },
      {
        id: 'M-3',
        drugName: 'Saline Solution 500ml IV',
        batchNo: 'IV-22-A',
        quantity: 1200,
        unit: 'Bottles',
        status: 'Packed',
        location: 'Aisle 5, Bay 1',
      },
    ],
  },
  {
    id: 'ORD-8892',
    orderNumber: 'ORD-8892',
    destination: 'Central City Hospital',
    requestedDate: 'Oct 24, 11:00 AM',
    status: 'Pending Ack.',
    priority: true,
    clearedForDispatch: false,
    slaLimit: '2 hrs remaining',
    totalValue: '₹24,800',
    transportDocStatus: 'Pending Generation',
    manifest: [
      {
        id: 'M-4',
        drugName: 'N95 Respirators & PPE Kits',
        batchNo: 'PPE-409',
        quantity: 1000,
        unit: 'Kits',
        status: 'Pending',
      },
      {
        id: 'M-5',
        drugName: 'Sterile Surgical Gloves 7.5',
        batchNo: 'GLV-112',
        quantity: 3000,
        unit: 'Pairs',
        status: 'Pending',
      },
    ],
  },
  {
    id: 'ORD-8845',
    orderNumber: 'ORD-8845',
    destination: 'Northside Clinic',
    requestedDate: 'Oct 23, 04:15 PM',
    status: 'Preparing',
    priority: false,
    clearedForDispatch: false,
    slaLimit: 'Tomorrow, 14:00',
    totalValue: '₹6,200',
    transportDocStatus: 'Pending Generation',
    manifest: [
      {
        id: 'M-6',
        drugName: 'Azithromycin 500mg',
        batchNo: 'AZ-771',
        quantity: 800,
        unit: 'Tabs',
        status: 'Packed',
      },
      {
        id: 'M-7',
        drugName: 'Cetirizine 10mg',
        batchNo: 'CT-220',
        quantity: 1500,
        unit: 'Tabs',
        status: 'Packed',
      },
    ],
  },
  {
    id: 'ORD-8812',
    orderNumber: 'ORD-8812',
    destination: 'West Valley Medical',
    requestedDate: 'Oct 23, 01:00 PM',
    status: 'In Transit',
    priority: false,
    clearedForDispatch: true,
    slaLimit: 'Today, 18:00',
    totalValue: '₹12,900',
    transportDocStatus: 'Dispatched',
    manifest: [
      {
        id: 'M-8',
        drugName: 'Ciprofloxacin 250mg',
        batchNo: 'A-402',
        quantity: 8500,
        unit: 'Tabs',
        status: 'Packed',
      },
    ],
  },
];

export const initialCentralLedger = [
  {
    id: 'LEDGER-1',
    name: 'Paracetamol 500mg',
    batchNo: 'B-881',
    location: 'Aisle 4, Shelf B',
    stock: 14200,
    unit: 'Tabs',
    status: 'optimal',
  },
  {
    id: 'LEDGER-2',
    name: 'Insulin Glargine',
    batchNo: 'C-112',
    location: 'Cold Storage 1',
    stock: 150,
    unit: 'Vials',
    status: 'low',
    warning: 'Low: 150',
  },
  {
    id: 'LEDGER-3',
    name: 'Ciprofloxacin 250mg',
    batchNo: 'A-402',
    location: 'Aisle 2, Shelf A',
    stock: 8500,
    unit: 'Tabs',
    status: 'optimal',
  },
  {
    id: 'LEDGER-4',
    name: 'Amoxicillin 500mg Caps',
    batchNo: 'B-992-X',
    location: 'Aisle 2, Shelf A',
    stock: 18400,
    unit: 'Caps',
    status: 'optimal',
  },
  {
    id: 'LEDGER-5',
    name: 'Saline Solution 500ml IV',
    batchNo: 'IV-22-A',
    location: 'Aisle 5, Bay 1',
    stock: 9600,
    unit: 'Bottles',
    status: 'optimal',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'V-1',
    name: 'MediEquip Global',
    fulfillmentRate: 98.5,
    avgDelay: '0.5 days',
    qualityRating: 4.8,
    status: 'Excellent',
    activeOrders: 18,
    contactEmail: 'logistics@mediequip.com',
  },
  {
    id: 'V-2',
    name: 'PharmaCorp Ind.',
    fulfillmentRate: 82.1,
    avgDelay: '3.2 days',
    qualityRating: 3.0,
    status: 'Under Review',
    activeOrders: 9,
    contactEmail: 'support@pharmacorp.in',
  },
  {
    id: 'V-3',
    name: 'Lifeline Logistics',
    fulfillmentRate: 95.0,
    avgDelay: '1.1 days',
    qualityRating: 4.0,
    status: 'Good',
    activeOrders: 14,
    contactEmail: 'dispatch@lifelinelog.org',
  },
  {
    id: 'V-4',
    name: 'Apex BioPharma Supplies',
    fulfillmentRate: 97.2,
    avgDelay: '0.8 days',
    qualityRating: 4.5,
    status: 'Excellent',
    activeOrders: 11,
    contactEmail: 'contact@apexbiopharma.com',
  },
];

export const initialHeatmapNodes: HeatmapNode[] = [
  {
    id: 'NODE-1',
    name: 'District Alpha Medical Complex',
    type: 'Major Hospital',
    coordinates: { x: 38, y: 32 },
    status: 'critical',
    stockLevelPercent: 24,
    criticalItems: ['Paracetamol < 5 days', 'Amoxicillin: Out of stock'],
    bedCapacity: 650,
    lastUpdated: '12m ago',
  },
  {
    id: 'NODE-2',
    name: 'Primary Health Centre Malda',
    type: 'PHC Clinic',
    coordinates: { x: 48, y: 68 },
    status: 'warning',
    stockLevelPercent: 52,
    criticalItems: ['Oxytocin (Low)', 'Saline IV (42 Units)'],
    bedCapacity: 80,
    lastUpdated: '5m ago',
  },
  {
    id: 'NODE-3',
    name: 'Central State Medical Warehouse',
    type: 'Central Warehouse',
    coordinates: { x: 62, y: 44 },
    status: 'optimal',
    stockLevelPercent: 91,
    criticalItems: [],
    bedCapacity: 0,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-4',
    name: 'North Wing General Hospital',
    type: 'Major Hospital',
    coordinates: { x: 55, y: 22 },
    status: 'critical',
    stockLevelPercent: 31,
    criticalItems: ['Insulin Glargine < 48hr', 'PPE Kits (Critical)'],
    bedCapacity: 480,
    lastUpdated: '18m ago',
  },
  {
    id: 'NODE-5',
    name: 'Siliguri Regional Depot',
    type: 'District Hub',
    coordinates: { x: 74, y: 36 },
    status: 'optimal',
    stockLevelPercent: 88,
    criticalItems: [],
    bedCapacity: 120,
    lastUpdated: '25m ago',
  },
  {
    id: 'NODE-6',
    name: 'Asansol Industrial Health Center',
    type: 'PHC Clinic',
    coordinates: { x: 28, y: 72 },
    status: 'warning',
    stockLevelPercent: 48,
    criticalItems: ['Antibiotic Vials near expiry'],
    bedCapacity: 60,
    lastUpdated: '40m ago',
  },
  {
    id: 'NODE-7',
    name: 'Kolkata Apex Medical Institute',
    type: 'Major Hospital',
    coordinates: { x: 52, y: 78 },
    status: 'optimal',
    stockLevelPercent: 94,
    criticalItems: [],
    bedCapacity: 1100,
    lastUpdated: '8m ago',
  },
];

export const initialUrgentAlerts: UrgentAlert[] = [
  {
    id: 'ALT-1',
    type: 'depletion',
    title: 'Insulin Depletion - Zone B',
    description: '3 major hospitals report < 48hr supply remaining.',
    severity: 'critical',
    timestamp: '10m ago',
    canReroute: true,
    associatedBatch: 'C-112',
  },
  {
    id: 'ALT-2',
    type: 'delay',
    title: 'Vendor Delay: PharmaCorp',
    description: 'Antibiotics shipment delayed by 2 days due to transit issues.',
    severity: 'warning',
    timestamp: '1h ago',
    associatedOrder: 'ORD-8815',
  },
  {
    id: 'ALT-3',
    type: 'expiry',
    title: 'Expiry Warning',
    description: 'Batch #8829 (Saline) expiring in 15 days at Central Warehouse.',
    severity: 'warning',
    timestamp: '3h ago',
    associatedBatch: 'IV-8829',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'INV-1',
    invoiceNumber: 'INV-2023-11',
    orderNumber: 'ORD-8812',
    destination: 'West Valley Medical',
    amount: 12900,
    status: 'Paid',
    issueDate: 'Oct 23, 2023',
    dueDate: 'Nov 23, 2023',
  },
  {
    id: 'INV-2',
    invoiceNumber: 'INV-2023-12',
    orderNumber: 'ORD-8845',
    destination: 'Northside Clinic',
    amount: 6200,
    status: 'Submitted',
    issueDate: 'Oct 24, 2023',
    dueDate: 'Nov 24, 2023',
  },
  {
    id: 'INV-3',
    invoiceNumber: 'INV-2023-13',
    orderNumber: 'ORD-8942',
    destination: 'City Hospital North Wing',
    amount: 18450,
    status: 'Draft',
    issueDate: 'Oct 24, 2023',
    dueDate: 'Nov 24, 2023',
  },
  {
    id: 'INV-4',
    invoiceNumber: 'INV-2023-14',
    orderNumber: 'ORD-8892',
    destination: 'Central City Hospital',
    amount: 24800,
    status: 'Awaiting Payment',
    issueDate: 'Oct 24, 2023',
    dueDate: 'Nov 24, 2023',
  },
];
